version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: todo_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: todo_app
      DB_USER: postgres
      DB_PASSWORD: root
    ports:
      - "80:80"
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./backend/config:/usr/local/apache2/htdocs/backend/config

volumes:
  postgres_data: